package com.techelevator.city.dao;

import java.util.ArrayList;
import java.util.List;

import javax.sql.DataSource;

import com.techelevator.city.dao.CityDAO;
import com.techelevator.city.model.City;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.rowset.SqlRowSet;

public class JDBCCityDAO implements CityDAO {

	private JdbcTemplate jdbcTemplate;
	
	public JDBCCityDAO(DataSource dataSource) {
		this.jdbcTemplate = new JdbcTemplate(dataSource);
	}


	/*
		INSERT a new City
	*/
	@Override
	public void create(City newCity) {
		String sqlInsertCity = "INSERT INTO city(id, name, countrycode, district, population) " +
							   "VALUES(DEFAULT, ?, ?, ?, ?) RETURNING id";


		/*
			Since the id is generated by a sequence a RETURNING clause is used to return the new id after
			the insert.
			queryForOjbect() is then used to get the generated id, since it is a single value
		 */
		Long newCityId = jdbcTemplate.queryForObject(sqlInsertCity, Long.class,
										  newCity.getName(),
										  newCity.getCountryCode(),
										  newCity.getDistrict(),
										  newCity.getPopulation());

		// The returned id is set on the City object
		newCity.setId(newCityId);
	}


	/*
		SELECT single City by id
	*/
	@Override
	public City findCityById(long id) {
		City theCity = null;
		String sqlFindCityById = "SELECT id, name, countrycode, district, population "+
							   "FROM city "+
							   "WHERE id = ?";
		SqlRowSet results = jdbcTemplate.queryForRowSet(sqlFindCityById, id);
		if(results.next()) {
			theCity = mapRowToCity(results);
		}
		return theCity;
	}


	/*
		SELECT List of Cities by country code
	*/
	@Override
	public List<City> findCityByCountryCode(String countryCode) {
		ArrayList<City> cities = new ArrayList<>();
		String sqlFindCityByCountryCode = "SELECT id, name, countrycode, district, population "+
										   "FROM city "+
										   "WHERE countrycode = ?";
		SqlRowSet results = jdbcTemplate.queryForRowSet(sqlFindCityByCountryCode, countryCode);
		while(results.next()) {
			City theCity = mapRowToCity(results);
			cities.add(theCity);
		}
		return cities;
	}


	/*
		SELECT List of Cities by district and country code
	*/
	@Override
	public List<City> findCityByDistrict(String district, String countryCode) {
		ArrayList<City> cities = new ArrayList<>();
		String sqlFindCityByCountryCode = "SELECT id, name, countrycode, district, population "+
				"FROM city "+
				"WHERE countrycode = ? AND district = ?";
		SqlRowSet results = jdbcTemplate.queryForRowSet(sqlFindCityByCountryCode, countryCode, district);
		while(results.next()) {
			City theCity = mapRowToCity(results);
			cities.add(theCity);
		}
		return cities;
	}


	/*
		UPDATES a City
	*/
	@Override
	public void update(City city) {
		String updateSql = "UPDATE city SET name = ?, countrycode = ?, district = ?, population = ? WHERE id = ?";
		jdbcTemplate.update(updateSql, city.getName(), city.getCountryCode(),
				city.getDistrict(), city.getPopulation(), city.getId());
	}


	/*
		DELETES a City
	*/
	@Override
	public void delete(long id) {
		String deleteSql = "DELETE FROM city WHERE id = ?";
		jdbcTemplate.update(deleteSql, id);
	}



	/*
		Maps the current Row in the ResultSet and uses the data to create and return the Data Object
		RESUSABLE CODE USED BY ALL METHODS THAT RETURN A CITY OR LIST OF CITIES (SELECTS) 
	*/
	private City mapRowToCity(SqlRowSet results) {
		City theCity;
		theCity = new City();
		theCity.setId(results.getLong("id"));
		theCity.setName(results.getString("name"));
		theCity.setCountryCode(results.getString("countrycode"));
		theCity.setDistrict(results.getString("district"));
		theCity.setPopulation(results.getInt("population"));
		return theCity;
	}
}
